# Generated by Django 2.0 on 2018-04-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cookbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名称')),
                ('img_url', models.CharField(max_length=200, verbose_name='图片源')),
                ('makings', models.CharField(max_length=800, verbose_name='材料')),
                ('work', models.CharField(max_length=2000, verbose_name='做法')),
                ('knack', models.CharField(max_length=500, verbose_name='诀窍')),
                ('family', models.CharField(max_length=100, verbose_name='类别')),
                ('pub_date', models.DateTimeField(verbose_name='时间')),
            ],
        ),
    ]
